# Generated by Django 5.2.5 on 2025-08-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado')], default='pendente', max_length=20),
        ),
    ]
